version: '3.9'

services:
  api:
    build: ./api
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./api:/api
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"

  client:
    build: ./client
    command: ["npm", "start"]
    volumes:
      - ./client:/client
      - node-modules:/client/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3030:3030'
    depends_on:
      - api

volumes:
  node-modules: